development:
  sessions:
    default:
      database: <%= ENV['MONGOID_DB'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      username: <%= ENV['MONGOID_USER'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      options:
  options:

test:
  sessions:
    default:
      database: <%= ENV['MONGOID_DB'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      username: <%= ENV['MONGOID_USER'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
        skip_version_check: true
        safe: true

production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DB'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      username: <%= ENV['MONGOID_USER'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      options:
        max_retries: 1
        retry_interval: 0
        skip_version_check: true
        safe: true
